### ISSUE TITLE
Cannot add Credentials to an existing user

### ISSUE THREAD

**Issue by YRodriguez** [kuzzleio/kuzzle-plugin-auth-passport-oauth#28]
## Expected Behavior
When using multiple strategies, I should add credentials informations even if a user is created.

## Current Behavior
When trying to add a new credential to an existing user, based on a new strategy, an error is raised : `Unable to find <strategy> with id 'xxx'`.

## Possible Solution
It seems that the error is raised in `validate()` method, because the call to `this.getProviderRepository(provider).get(...)` now throw a NotFoundError, and is no handled.

## Steps to Reproduce

1. Configure 2 strategies in oauth-plugin
2. Create a user with one Strategy
3. Try to add a new strategy to this existing user

## Context (Environment)

Kuzzle 1.5.1
oauth-plugin 4.0.9

**Comment by Aschen** [comment]
This issue is fixed since a long time (even in Kuzzle v1)
