### ISSUE TITLE
multiple kuzzle instances on same elasticsearch

### ISSUE THREAD

**Issue by Perfect-Web** [kuzzleio/kuzzle-plugin-auth-passport-oauth#40]
## Expected Behavior

it should work

## Current Behavior

conflicts

## Steps to Reproduce

if you run multiple kuzzle instalations on the same elasticsearch cluster, you are unable to provide full isolations because the kuzzle plugin auth passport will conflict

**Comment by alexandrebouthinon** [comment]
Hi @Perfect-Web, by "multiple Kuzzle instances" did you mean as a cluster or not?

**Comment by Perfect-Web** [comment]
@alexandrebouthinon no, i mean multiple separate clients/ totally independent installs that work on the same es cluster

**Comment by alexandrebouthinon** [comment]
> @alexandrebouthinon no, i mean multiple separate clients/ totally independent installs that work on the same es cluster

This is not supported at this time. Depending on your use case there may be another way to do it using only one Kuzzle cluster. Could you provide us with more information?

**Comment by alexandrebouthinon** [comment]
@Perfect-Web Depending on your use case it may have another way

**Comment by Perfect-Web** [comment]
@alexandrebouthinon what more info ? i think i gave you all the info :) is simple as that, 1 es cluster, multiple kuzzle instances (1 per client)

the auth plugin will collision among all kuzzle instances because it will create the same index name, irrespective of the internalIndex name set in kuzzlerc

**Comment by alexandrebouthinon** [comment]
@Perfect-Web I mean, what inspired you to come up with this architecture?

**Comment by Perfect-Web** [comment]
@alexandrebouthinon the need :)

**Comment by alexandrebouthinon** [comment]
@Perfect-Web Kuzzle is currently not designed to use an Elasticsearch cluster together with other instances. It is not documented and therefore not supported at least for the moment.

**Comment by Perfect-Web** [comment]
@alexandrebouthinon that is not entirely true. i have a way that works, u just have to setup custom internalIndex name for each index, on top of that, the only think that needs to be modified and im doing this the hard way now, is before startup, to rename the auth-passport plugin and prefix it with something so it doesnt collision with the other indexes. the result is that each auth plugin index inside es will have the different name

**Comment by alexandrebouthinon** [comment]
@Perfect-Web Sounds like more of a hack to me than anything else :wink: . I'm pretty sure there's another architecture design that might work better. Could you explain your business need?

**Comment by Perfect-Web** [comment]
@alexandrebouthinon yes, it is a hack. I would expect any piece of software to implement best practices. Since kuzzle is able to operate on different es indexes i do not see why this plugin doesnt follow the same pattern (im not judging, just stating the obvious :) )

**Comment by alexandrebouthinon** [comment]
Likewise, I'm not judging. I'm trying to understand the use case.

**Comment by Aschen** [comment]
Actually Kuzzle support multi tenancy very easily with the right management system so you only need multiple Kuzzle instances if you have totally different application.

**Comment by Aschen** [comment]
This feature has been added to our product workshop, we will discuss it soon.
